LangToMarcCode = {
"Afar" : "aar",
"Abkhaz" : "abk",
"Achinese" : "ace",
"Acoli" : "ach",
"Adangme" : "ada",
"Adygei" : "ady",
"Afroasiatic (Other)" : "afa",
"Afrihili (Artificial language)" : "afh",
"Afrikaans" : "afr",
"Ainu" : "ain",
"Akan" : "aka",
"Akkadian" : "akk",
"Albanian" : "alb",
"Aleut" : "ale",
"Algonquian (Other)" : "alg",
"Altai" : "alt",
"Amharic" : "amh",
"English, Old (ca. 450-1100)" : "ang",
"Angika" : "anp",
"Apache languages" : "apa",
"Arabic" : "ara",
"Aramaic" : "arc",
"Aragonese" : "arg",
"Armenian" : "arm",
"Mapuche" : "arn",
"Arapaho" : "arp",
"Artificial (Other)" : "art",
"Arawak" : "arw",
"Assamese" : "asm",
"Bable" : "ast",
"Athapascan (Other)" : "ath",
"Australian languages" : "aus",
"Avaric" : "ava",
"Avestan" : "ave",
"Awadhi" : "awa",
"Aymara" : "aym",
"Azerbaijani" : "aze",
"Banda languages" : "bad",
"Bamileke languages" : "bai",
"Bashkir" : "bak",
"Baluchi" : "bal",
"Bambara" : "bam",
"Balinese" : "ban",
"Basque" : "baq",
"Basa" : "bas",
"Baltic (Other)" : "bat",
"Beja" : "bej",
"Belarusian" : "bel",
"Bemba" : "bem",
"Bengali" : "ben",
"Berber (Other)" : "ber",
"Bhojpuri" : "bho",
"Bihari (Other)" : "bih",
"Bikol" : "bik",
"Edo" : "bin",
"Bislama" : "bis",
"Siksika" : "bla",
"Bantu (Other)" : "bnt",
"Bosnian" : "bos",
"Braj" : "bra",
"Breton" : "bre",
"Batak" : "btk",
"Buriat" : "bua",
"Bugis" : "bug",
"Bulgarian" : "bul",
"Burmese" : "bur",
"Bilin" : "byn",
"Caddo" : "cad",
"Central American Indian (Other)" : "cai",
"Carib" : "car",
"Catalan" : "cat",
"Caucasian (Other)" : "cau",
"Cebuano" : "ceb",
"Celtic (Other)" : "cel",
"Chamorro" : "cha",
"Chibcha" : "chb",
"Chechen" : "che",
"Chagatai" : "chg",
"Chinese" : "chi",
"Chuukese" : "chk",
"Mari" : "chm",
"Chinook jargon" : "chn",
"Choctaw" : "cho",
"Chipewyan" : "chp",
"Cherokee" : "chr",
"Church Slavic" : "chu",
"Chuvash" : "chv",
"Cheyenne" : "chy",
"Chamic languages" : "cmc",
"Coptic" : "cop",
"Cornish" : "cor",
"Corsican" : "cos",
"Creoles and Pidgins, English-based (Other)" : "cpe",
"Creoles and Pidgins, French-based (Other)" : "cpf",
"Creoles and Pidgins, Portuguese-based (Other)" : "cpp",
"Cree" : "cre",
"Crimean Tatar" : "crh",
"Creoles and Pidgins (Other)" : "crp",
"Kashubian" : "csb",
"Cushitic (Other)" : "cus",
"Czech" : "cze",
"Dakota" : "dak",
"Danish" : "dan",
"Dargwa" : "dar",
"Dayak" : "day",
"Delaware" : "del",
"Slavey" : "den",
"Dogrib" : "dgr",
"Dinka" : "din",
"Divehi" : "div",
"Dogri" : "doi",
"Dravidian (Other)" : "dra",
"Lower Sorbian" : "dsb",
"Duala" : "dua",
"Dutch, Middle (ca. 1050-1350)" : "dum",
"Dutch" : "dut",
"Dyula" : "dyu",
"Dzongkha" : "dzo",
"Efik" : "efi",
"Egyptian" : "egy",
"Ekajuk" : "eka",
"Elamite" : "elx",
"English" : "eng",
"English, Middle (1100-1500)" : "enm",
"Esperanto" : "epo",
"Estonian" : "est",
"Ewe" : "ewe",
"Ewondo" : "ewo",
"Fang" : "fan",
"Faroese" : "fao",
"Fanti" : "fat",
"Fijian" : "fij",
"Filipino" : "fil",
"Finnish" : "fin",
"Finno-Ugrian (Other)" : "fiu",
"Fon" : "fon",
"French" : "fre",
"French, Middle (ca. 1300-1600)" : "frm",
"French, Old (ca. 842-1300)" : "fro",
"North Frisian" : "frr",
"East Frisian" : "frs",
"Frisian" : "fry",
"Fula" : "ful",
"Friulian" : "fur",
"Gayo" : "gay",
"Gbaya" : "gba",
"Germanic (Other)" : "gem",
"Georgian" : "geo",
"German" : "ger",
"Ethiopic" : "gez",
"Gilbertese" : "gil",
"Scottish Gaelic" : "gla",
"Irish" : "gle",
"Galician" : "glg",
"Manx" : "glv",
"German, Middle High (ca. 1050-1500)" : "gmh",
"German, Old High (ca. 750-1050)" : "goh",
"Gondi" : "gon",
"Gorontalo" : "gor",
"Gothic" : "got",
"Grebo" : "grb",
"Greek, Ancient (to 1453)" : "grc",
"Greek, Modern (1453-)" : "gre",
"Guarani" : "grn",
"Swiss German" : "gsw",
"Gujarati" : "guj",
"Gwich'in" : "gwi",
"Haida" : "hai",
"Haitian French Creole" : "hat",
"Hausa" : "hau",
"Hawaiian" : "haw",
"Hebrew" : "heb",
"Herero" : "her",
"Hiligaynon" : "hil",
"Western Pahari languages" : "him",
"Hindi" : "hin",
"Hittite" : "hit",
"Hmong" : "hmn",
"Hiri Motu" : "hmo",
"Croatian" : "hrv",
"Upper Sorbian" : "hsb",
"Hungarian" : "hun",
"Hupa" : "hup",
"Iban" : "iba",
"Igbo" : "ibo",
"Icelandic" : "ice",
"Ido" : "ido",
"Sichuan Yi" : "iii",
"Ijo" : "ijo",
"Inuktitut" : "iku",
"Interlingue" : "ile",
"Iloko" : "ilo",
"Interlingua (International Auxiliary Language Association)" : "ina",
"Indic (Other)" : "inc",
"Indonesian" : "ind",
"Indo-European (Other)" : "ine",
"Ingush" : "inh",
"Inupiaq" : "ipk",
"Iranian (Other)" : "ira",
"Iroquoian (Other)" : "iro",
"Italian" : "ita",
"Javanese" : "jav",
"Lojban (Artificial language)" : "jbo",
"Japanese" : "jpn",
"Judeo-Persian" : "jpr",
"Judeo-Arabic" : "jrb",
"Kara-Kalpak" : "kaa",
"Kabyle" : "kab",
"Kachin" : "kac",
"Kamba" : "kam",
"Kannada" : "kan",
"Karen languages" : "kar",
"Kashmiri" : "kas",
"Kanuri" : "kau",
"Kawi" : "kaw",
"Kazakh" : "kaz",
"Kabardian" : "kbd",
"Khasi" : "kha",
"Khoisan (Other)" : "khi",
"Khmer" : "khm",
"Khotanese" : "kho",
"Kikuyu" : "kik",
"Kinyarwanda" : "kin",
"Kyrgyz" : "kir",
"Kimbundu" : "kmb",
"Konkani" : "kok",
"Komi" : "kom",
"Kongo" : "kon",
"Korean" : "kor",
"Kosraean" : "kos",
"Kpelle" : "kpe",
"Karachay-Balkar" : "krc",
"Karelian" : "krl",
"Kru (Other)" : "kro",
"Kurukh" : "kru",
"Kuanyama" : "kua",
"Kumyk" : "kum",
"Kurdish" : "kur",
"Kootenai" : "kut",
"Ladino" : "lad",
"Lahnd?" : "lah",
"Lamba (Zambia and Congo)" : "lam",
"Lao" : "lao",
"Latin" : "lat",
"Latvian" : "lav",
"Lezgian" : "lez",
"Limburgish" : "lim",
"Lingala" : "lin",
"Lithuanian" : "lit",
"Mongo-Nkundu" : "lol",
"Lozi" : "loz",
"Luxembourgish" : "ltz",
"Luba-Lulua" : "lua",
"Luba-Katanga" : "lub",
"Ganda" : "lug",
"Lunda" : "lun",
"Luo (Kenya and Tanzania)" : "luo",
"Lushai" : "lus",
"Macedonian" : "mac",
"Madurese" : "mad",
"Magahi" : "mag",
"Marshallese" : "mah",
"Maithili" : "mai",
"Makasar" : "mak",
"Malayalam" : "mal",
"Mandingo" : "man",
"Maori" : "mao",
"Austronesian (Other)" : "map",
"Marathi" : "mar",
"Maasai" : "mas",
"Malay" : "may",
"Moksha" : "mdf",
"Mandar" : "mdr",
"Mende" : "men",
"Irish, Middle (ca. 1100-1550)" : "mga",
"Micmac" : "mic",
"Minangkabau" : "min",
"Miscellaneous languages" : "mis",
"Mon-Khmer (Other)" : "mkh",
"Malagasy" : "mlg",
"Maltese" : "mlt",
"Manchu" : "mnc",
"Manipuri" : "mni",
"Manobo languages" : "mno",
"Mohawk" : "moh",
"Mongolian" : "mon",
"Multiple languages" : "mul",
"Munda (Other)" : "mun",
"Creek" : "mus",
"Mirandese" : "mwl",
"Marwari" : "mwr",
"Mayan languages" : "myn",
"Erzya" : "myv",
"Nahuatl" : "nah",
"North American Indian (Other)" : "nai",
"Neapolitan Italian" : "nap",
"Nauru" : "nau",
"Navajo" : "nav",
"Ndebele (South Africa)" : "nbl",
"Ndebele (Zimbabwe)" : "nde",
"Ndonga" : "ndo",
"Low German" : "nds",
"Nepali" : "nep",
"Newari" : "new",
"Nias" : "nia",
"Niger-Kordofanian (Other)" : "nic",
"Niuean" : "niu",
"Norwegian (Nynorsk)" : "nno",
"Nogai" : "nog",
"Old Norse" : "non",
"Norwegian" : "nor",
"N'Ko" : "nqo",
"Northern Sotho" : "nso",
"Nubian languages" : "nub",
"Newari, Old" : "nwc",
"Nyanja" : "nya",
"Nyamwezi" : "nym",
"Nyankole" : "nyn",
"Nyoro" : "nyo",
"Nzima" : "nzi",
"Occitan (post 1500)" : "oci",
"Ojibwa" : "oji",
"Oriya" : "ori",
"Oromo" : "orm",
"Osage" : "osa",
"Ossetic" : "oss",
"Turkish, Ottoman" : "ota",
"Otomian languages" : "oto",
"Papuan (Other)" : "paa",
"Pangasinan" : "pag",
"Pahlavi" : "pal",
"Pampanga" : "pam",
"Panjabi" : "pan",
"Papiamento" : "pap",
"Palauan" : "pau",
"Old Persian (ca. 600-400 B.C.)" : "peo",
"Persian" : "per",
"Philippine (Other)" : "phi",
"Phoenician" : "phn",
"Pali" : "pli",
"Polish" : "pol",
"Pohnpeian" : "pon",
"Portuguese" : "por",
"Prakrit languages" : "pra",
"Pushto" : "pus",
"Quechua" : "que",
"Rajasthani" : "raj",
"Rapanui" : "rap",
"Rarotongan" : "rar",
"Romance (Other)" : "roa",
"Raeto-Romance" : "roh",
"Romani" : "rom",
"Romanian" : "rum",
"Rundi" : "run",
"Aromanian" : "rup",
"Russian" : "rus",
"Sandawe" : "sad",
"Sango (Ubangi Creole)" : "sag",
"Yakut" : "sah",
"South American Indian (Other)" : "sai",
"Salishan languages" : "sal",
"Samaritan Aramaic" : "sam",
"Sanskrit" : "san",
"Sasak" : "sas",
"Santali" : "sat",
"Sicilian Italian" : "scn",
"Scots" : "sco",
"Selkup" : "sel",
"Semitic (Other)" : "sem",
"Irish, Old (to 1100)" : "sga",
"Sign languages" : "sgn",
"Shan" : "shn",
"Sidamo" : "sid",
"Sinhalese" : "sin",
"Siouan (Other)" : "sio",
"Sino-Tibetan (Other)" : "sit",
"Slavic (Other)" : "sla",
"Slovak" : "slo",
"Slovenian" : "slv",
"Southern Sami" : "sma",
"Northern Sami" : "sme",
"Sami" : "smi",
"Lule Sami" : "smj",
"Inari Sami" : "smn",
"Samoan" : "smo",
"Skolt Sami" : "sms",
"Shona" : "sna",
"Sindhi" : "snd",
"Soninke" : "snk",
"Sogdian" : "sog",
"Somali" : "som",
"Songhai" : "son",
"Sotho" : "sot",
"Spanish" : "spa",
"Sardinian" : "srd",
"Sranan" : "srn",
"Serbian" : "srp",
"Serer" : "srr",
"Nilo-Saharan (Other)" : "ssa",
"Swazi" : "ssw",
"Sukuma" : "suk",
"Sundanese" : "sun",
"Susu" : "sus",
"Sumerian" : "sux",
"Swahili" : "swa",
"Swedish" : "swe",
"Syriac" : "syc",
"Syriac, Modern" : "syr",
"Tahitian" : "tah",
"Tai (Other)" : "tai",
"Tamil" : "tam",
"Tatar" : "tat",
"Telugu" : "tel",
"Temne" : "tem",
"Terena" : "ter",
"Tetum" : "tet",
"Tajik" : "tgk",
"Tagalog" : "tgl",
"Thai" : "tha",
"Tibetan" : "tib",
"Tigrinya" : "tir",
"Tiv" : "tiv",
"Tokelauan" : "tkl",
"Klingon (Artificial language)" : "tlh",
"Tlingit" : "tli",
"Tamashek" : "tmh",
"Tonga (Nyasa)" : "tog",
"Tongan" : "ton",
"Tok Pisin" : "tpi",
"Tsimshian" : "tsi",
"Tswana" : "tsn",
"Tsonga" : "tso",
"Turkmen" : "tuk",
"Tumbuka" : "tum",
"Tupi languages" : "tup",
"Turkish" : "tur",
"Altaic (Other)" : "tut",
"Tuvaluan" : "tvl",
"Twi" : "twi",
"Tuvinian" : "tyv",
"Udmurt" : "udm",
"Ugaritic" : "uga",
"Uighur" : "uig",
"Ukrainian" : "ukr",
"Umbundu" : "umb",
"Undetermined" : "und",
"Urdu" : "urd",
"Uzbek" : "uzb",
"Vai" : "vai",
"Venda" : "ven",
"Vietnamese" : "vie",
"Votic" : "vot",
"Wakashan languages" : "wak",
"Wolayta" : "wal",
"Waray" : "war",
"Washoe" : "was",
"Welsh" : "wel",
"Sorbian (Other)" : "wen",
"Walloon" : "wln",
"Wolof" : "wol",
"Oirat" : "xal",
"Xhosa" : "xho",
"Yao (Africa)" : "yao",
"Yapese" : "yap",
"Yiddish" : "yid",
"Yoruba" : "yor",
"Yupik languages" : "ypk",
"Zapotec" : "zap",
"Blissymbolics" : "zbl",
"Zenaga" : "zen",
"Zhuang" : "zha",
"Zande languages" : "znd",
"Zulu" : "zul",
"Zuni" : "zun",
"No linguistic content" : "zxx",
"Zaza" : "zza",
}
